// Generated by CoffeeScript 1.12.7
(function() {
  var handleChangeDropdownMultiselectMenu, handleClickDocument, handleClickDropdownMultiselectMenu, handleClickDropdownMultiselectToggle, updateSelectedText;

  window.selectedValues = {};

  updateSelectedText = function($target, values) {
    var $selectedText, firstSelected, otherSelectedCount;
    $selectedText = $target.closest('.dropdown-multiselect').find('.dropdown-multiselect-title');
    if (values.length > 0) {
      firstSelected = values[0];
      otherSelectedCount = values.length - 1;
      if (otherSelectedCount > 0) {
        $selectedText.text(firstSelected + " +" + otherSelectedCount);
        return $selectedText.addClass('bold');
      } else {
        $selectedText.text(firstSelected);
        return $selectedText.addClass('bold');
      }
    } else {
      $selectedText.text($selectedText.data('title'));
      return $selectedText.removeClass('bold');
    }
  };

  handleClickDropdownMultiselectToggle = function(e) {
    e.preventDefault();
    e.stopPropagation();
    return $(e.target).closest('.dropdown-multiselect').toggleClass('open');
  };

  handleClickDropdownMultiselectMenu = function(e) {
    var $checkbox, $label;
    $label = $(e.target);
    if ($label) {
      $checkbox = $label.find('input[type="checkbox"]');
      $checkbox.prop('checked', !$checkbox.is(':checked'));
      return $checkbox.trigger('change');
    }
  };

  handleChangeDropdownMultiselectMenu = function(e) {
    var $target, value;
    $target = $(e.target);
    if (!window.selectedValues[$target.data('group-id')]) {
      window.selectedValues[$target.data('group-id')] = [];
    }
    if ($target && $target.attr('type') === 'checkbox') {
      value = $target.data('name');
      if ($target.is(':checked')) {
        window.selectedValues[$target.data('group-id')].push(value);
      } else {
        window.selectedValues[$target.data('group-id')] = window.selectedValues[$target.data('group-id')].filter(function(v) {
          return v !== value;
        });
      }
      return updateSelectedText($target, window.selectedValues[$target.data('group-id')]);
    }
  };

  handleClickDocument = function(e) {
    if ($(e.target).closest('.dropdown-multiselect').length === 0) {
      return $(document).find('.dropdown-multiselect').removeClass('open');
    }
  };

  $(document).on('click', '.dropdown-multiselect-toggle', handleClickDropdownMultiselectToggle);

  $(document).on('click', '.dropdown-multiselect-menu-item', handleClickDropdownMultiselectMenu);

  $(document).on('change', '.dropdown-multiselect-menu-item', handleChangeDropdownMultiselectMenu);

  $(document).on('click', handleClickDocument);

}).call(this);
